### ISSUE TITLE
脱离idea运行dynamic-provider安装失败。

### ISSUE THREAD

**Issue by yupd** [sofastack-guides/sofa-ark-dynamic-guides#14]
022-06-22 18:42:28,262 ERROR SOFA-ARK-telnet-command-1-T1     - Install Biz: dynamic-provider:1.0.0 fail,cost: 42 ms, started at: 18:42:28,218
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:285)
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:172)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:348)
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:333)
	at com.alipay.sofa.ark.container.service.biz.BizCommandProvider$BizCommand$1.run(BizCommandProvider.java:249)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at io.sofastack.dynamic.provider.ProviderApplication.main(ProviderApplication.java:15)
	... 13 common frames omitted
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: Post find class org.springframework.boot.SpringApplication occurs an error via biz ClassLoaderHook: com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook@1c5986cb.
Caused by: java.lang.IllegalArgumentException: File must exist
	at com.alipay.sofa.ark.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67)
	at com.alipay.sofa.ark.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51)
	at com.alipay.sofa.ark.loader.jar.JarFile.<init>(JarFile.java:83)
	at com.alipay.sofa.ark.container.model.BizModel.doCheckDeclared(BizModel.java:469)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.alipay.sofa.ark.container.model.BizModel.checkDeclaredWithCache(BizModel.java:458)
	at com.alipay.sofa.ark.container.model.BizModel.isDeclared(BizModel.java:423)
	at com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook.postFindClass(DelegateToMasterBizClassLoaderHook.java:55)
	at com.alipay.sofa.ark.support.common.DelegateToMasterBizClassLoaderHook.postFindClass(DelegateToMasterBizClassLoaderHook.java:35)
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.postLoadClass(BizClassLoader.java:197)
	at com.alipay.sofa.ark.container.service.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:127)
	at com.alipay.sofa.ark.container.service.classloader.AbstractClasspathClassLoader.lambda$loadClassWithCache$0(AbstractClasspathClassLoader.java:207)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)

**Comment by lvjing2** [comment]
你好，麻烦拉下最新代码试下。

**Comment by lvjing2** [comment]
之前没验过 java -jar 启动，现在验过ok了。

**Comment by yupd** [comment]
给力！
