### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by xiamy-summer** [sofastack-guides/sofa-ark-dynamic-guides#6]
Exception in thread "main" java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:66)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at io.sofastack.stockmng.StockMngApplication.main(StockMngApplication.java:16)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:59)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArk(ArkApplicationStartListener.java:72)
	at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:58)
	... 11 more
Caused by: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.thread.IsolatedThreadGroup.rethrowUncaughtException(IsolatedThreadGroup.java:50)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:55)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:104)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:73)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:77)
	... 6 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: start serverless runtime plugin error
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:81)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:149)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:110)
	... 14 more
Caused by: com.alipay.sofa.ark.exception.ArkRuntimeException: start serverless runtime plugin error
	at com.alipay.sofa.ark.container.model.PluginModel.start(PluginModel.java:327)
	at com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl.deployPlugin(PluginDeployServiceImpl.java:61)
	at com.alipay.sofa.ark.container.service.plugin.PluginDeployServiceImpl.deploy(PluginDeployServiceImpl.java:49)
	at com.alipay.sofa.ark.container.pipeline.DeployPluginStage.process(DeployPluginStage.java:45)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75)
	... 16 more
Caused by: java.lang.RuntimeException: start serverless runtime plugin error
	at com.alipay.sofa.boot.ark.activator.SOFABootRuntimeActivator.start(SOFABootRuntimeActivator.java:41)
	at com.alipay.sofa.ark.container.model.PluginModel.start(PluginModel.java:325)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/alipay/sofa/runtime/SofaBizUninstallEventHandler
	at com.alipay.sofa.boot.ark.activator.SOFABootRuntimeActivator.registerEventHandler(SOFABootRuntimeActivator.java:48)
	at com.alipay.sofa.boot.ark.activator.SOFABootRuntimeActivator.start(SOFABootRuntimeActivator.java:37)
	... 21 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkPlugin Loader] sofaboot-ark-plugin : can not load class: com.alipay.sofa.runtime.SofaBizUninstallEventHandler

**Comment by lvjing2** [comment]
按照readme里，带上 -Dsofa.ark.embed.enable=true 了吗？

**Comment by xiamy-summer** [comment]
好的我明白了。
